# Generated by Django 5.2.8 on 2025-11-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("image", models.URLField()),
                ("release_date", models.DateField()),
                ("lte_exists", models.BooleanField(default=False)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
